server:
  port: 8081
spring:
  application:
    name: company
  graphql:
    graphiql:
      enabled: true
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info